spring:
  datasource:
    url: jdbc:mysql://chatbotai_postgresql:5432/chatbotai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

admin:
  signup:
    code : ${ADMIN_SIGNUP_CODE}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-time: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-time: ${JWT_REFRESH_TOKEN_TIME}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core: DEBUG
